### ISSUE TITLE
License Arduino-Hex-Decimal-Conversion

### ISSUE THREAD

**Issue by shafeeqr2** [benrugg/Arduino-Hex-Decimal-Conversion#1]
Hi,

I was wondering what is the license for the Arduino-Hex-Decimal-Conversion?
Are we free to use this, modify it?
I am currently developing an application which might become commercial one day. One of the things this application needed was a Hex to Dec converter and a Dec to Hex converter. Hence, I am contacting you for permission to use this code for the purpose stated above.

Regards,

Shafeeq Rabbani.

**Comment by benrugg** [comment]
Hey @shafeeqr2 - yes, please feel free to use it for any purpose you like, or modify it, etc. I just added the MIT license so now it's officially open :-)
